"use client";

import { useEffect, useMemo, useState } from "react";
import ThematicMap from "../mapkit/thematic-map";

type CountyContext={residentPopulationWan:number;constructionAreaHa:number;commercialAreaHa:number;industryLogisticsAreaHa:number;publicServiceAreaHa:number;gatewayAreaHa:number};
type CategoryNode={name:string;count:number;children?:CategoryNode[]};
type Payload={meta:{source:string;countyCount:number;categoryCount:number;majorCategoryCount:number;middleCategoryCount:number;minorCategoryCount:number;poiTotal:number;functionalPoiTotal:number;excludedFunctionalRows:number;duplicateFunctionalRows:number;functionalCategories:string[];functionalRule:string;renamedCounties:Record<string,string>;excludedCountyNames:string[];rule:string;populationSource:string;populationYear:string;landSource:string;normalizationRule:string};countyBoundaries:{features:any[]};categoryTree:CategoryNode[];countyTotals:Record<string,number>;countyContext:Record<string,CountyContext>;functionalRecords:[string,string,string,number][];records:[string,string,string,string,string,number][]};
type Measure="count"|"share"|"per10k"|"perSqKm"|"lq"|"nodePerLand";
type PoiTopic="overview"|"structure"|"service"|"center"|"match";
type CategorySelection={level:0|1|2|3;major:string;middle:string;minor:string;path:string};
const measures:Record<Measure,{name:string;shortName:string;unit:string;digits:number;formula:string;meaning:string}>={
  count:{name:"POI数量",shortName:"数量",unit:"个",digits:0,formula:"区县内当前类别POI点位计数",meaning:"衡量设施或服务点的绝对规模，容易受区县人口和建成区规模影响。"},
  per10k:{name:"每万常住人口POI数",shortName:"人均供给",unit:"个/万人",digits:1,formula:"POI数量 ÷ 2024年常住人口（万人）",meaning:"用常住人口校正设施数量，用于比较不同人口规模区县的相对供给水平。"},
  perSqKm:{name:"建设用地POI密度",shortName:"空间密度",unit:"个/平方公里",digits:1,formula:"POI数量 ÷（建设用地公顷 ÷ 100）",meaning:"用建设用地规模校正点位数量，用于比较建成空间中的设施集聚密度。"},
  share:{name:"区县功能结构占比",shortName:"功能占比",unit:"%",digits:1,formula:"当前功能POI ÷ 区县全部有效功能型POI × 100%",meaning:"衡量当前功能在区县节点结构中的份额，不代表专业化程度。"},
  lq:{name:"POI功能区位熵 LQ",shortName:"专业化",unit:"",digits:2,formula:"区县当前功能占比 ÷ 都市圈当前功能占比",meaning:"LQ>1表示高于都市圈平均结构，LQ>1.2可作为初步专业化信号。"},
  nodePerLand:{name:"对应功能用地节点承载强度",shortName:"节点承载",unit:"个/平方公里",digits:1,formula:"当前功能POI ÷ 对应功能用地面积",meaning:"衡量单位对应功能用地承载的POI节点数，命名为承载强度而非土地利用效率。"},
};
const poiTopics:Record<PoiTopic,{name:string;question:string;measures:Measure[]}>= {overview:{name:"功能总体格局",question:"城市功能节点集中在哪里",measures:["count","perSqKm","per10k"]},structure:{name:"区县功能结构",question:"各区县主要承担什么城市功能",measures:["share","count","lq"]},service:{name:"公共服务配置",question:"设施节点相对常住人口是否充足",measures:["per10k","count"]},center:{name:"功能集聚与中心体系",question:"哪些区县具有综合中心或专业职能",measures:["lq","perSqKm","count"]},match:{name:"用地—POI匹配",question:"功能用地与活动节点是否匹配",measures:["nodePerLand","count"]}};
const fmt=(value:number,digits=0)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:digits}).format(value);
const parseCategory=(key:string):CategorySelection=>{const [level="0",major="",middle="",minor=""]=key.split("::");const numeric=Number(level) as 0|1|2|3;return{level:numeric,major,middle,minor,path:numeric===0?"全部POI类别":[major,middle,minor].filter(Boolean).join(" / ")}};

export default function PublicServicesModule(){
  const [data,setData]=useState<Payload|null>(null),[topic,setTopic]=useState<PoiTopic>("overview"),[city,setCity]=useState("全部"),[categoryMode,setCategoryMode]=useState<"分析分类"|"原始分类">("分析分类"),[functionalCategory,setFunctionalCategory]=useState("ALL"),[categoryKey,setCategoryKey]=useState("0::"),[measure,setMeasure]=useState<Measure>("count"),[selected,setSelected]=useState<string|null>(null);
  useEffect(()=>{fetch("/data/public-services.json").then(response=>response.json()).then(setData)},[]);
  useEffect(()=>setSelected(null),[city,categoryKey,functionalCategory,categoryMode,measure]);
  useEffect(()=>{setMeasure(poiTopics[topic].measures[0]);setCategoryMode("分析分类");setFunctionalCategory(topic==="overview"?"ALL":topic==="service"?"教育文化":"商业消费");setSelected(null)},[topic]);
  const countyCity=useMemo(()=>data?new Map(data.countyBoundaries.features.map(feature=>[feature.properties.name,feature.properties.city])):new Map<string,string>(),[data]);
  if(!data)return <section className="thematicLoading">正在载入公共服务设施数据…</section>;
  const category=parseCategory(categoryKey),matchesCategory=(row:Payload["records"][number])=>category.level===0||(row[2]===category.major&&(category.level===1||(row[3]===category.middle&&(category.level===2||row[4]===category.minor))));
  const functionalTotalByCounty=new Map<string,number>();for(const row of data.functionalRecords)functionalTotalByCounty.set(row[1],(functionalTotalByCounty.get(row[1])||0)+row[3]);
  const counties=[...countyCity.entries()].filter(([,value])=>city==="全部"||value===city).map(([county])=>county),active=new Set(counties),rawValues=new Map(counties.map(county=>[county,categoryMode==="分析分类"?data.functionalRecords.filter(row=>row[1]===county&&(functionalCategory==="ALL"||row[2]===functionalCategory)).reduce((sum,row)=>sum+row[3],0):data.records.filter(row=>row[1]===county&&matchesCategory(row)).reduce((sum,row)=>sum+row[5],0)])),definition=measures[measure];
  const metroSelected=data.functionalRecords.filter(row=>functionalCategory==="ALL"||row[2]===functionalCategory).reduce((sum,row)=>sum+row[3],0),metroShare=metroSelected/Math.max(1,data.meta.functionalPoiTotal);
  const landDenominator=(county:string)=>{const x=data.countyContext[county];if(["商业消费","餐饮休闲"].includes(functionalCategory))return{label:"商业服务用地",ha:x.commercialAreaHa};if(["产业就业","物流服务"].includes(functionalCategory))return{label:"工业及物流仓储用地",ha:x.industryLogisticsAreaHa};if(["公共管理","教育文化","医疗健康"].includes(functionalCategory))return{label:"公共服务用地",ha:x.publicServiceAreaHa};if(functionalCategory==="交通门户")return{label:"交通门户用地",ha:x.gatewayAreaHa};return{label:"建设用地",ha:x.constructionAreaHa}};
  const normalizedValue=(county:string)=>{const raw=rawValues.get(county)||0,context=data.countyContext[county];if(measure==="per10k")return context?.residentPopulationWan?raw/context.residentPopulationWan:0;if(measure==="perSqKm")return context?.constructionAreaHa?raw/(context.constructionAreaHa/100):0;if(measure==="share")return raw/Math.max(1,functionalTotalByCounty.get(county)||0)*100;if(measure==="lq")return metroShare?raw/Math.max(1,functionalTotalByCounty.get(county)||0)/metroShare:0;if(measure==="nodePerLand"){const land=landDenominator(county);return land.ha?raw/(land.ha/100):0}return raw};
  const values=new Map(counties.map(county=>[county,normalizedValue(county)])),ranked=[...values].sort((a,b)=>b[1]-a[1]),rawTotal=[...rawValues.values()].reduce((sum,value)=>sum+value,0),populationTotal=counties.reduce((sum,county)=>sum+(data.countyContext[county]?.residentPopulationWan||0),0),constructionTotal=counties.reduce((sum,county)=>sum+(data.countyContext[county]?.constructionAreaHa||0)/100,0),current=selected&&active.has(selected)?selected:ranked[0]?.[0],leader=ranked[0],categoryName=categoryMode==="分析分类"?(functionalCategory==="ALL"?"全部有效功能型POI":functionalCategory):category.path;
  const countyDetailMap=new Map<string,number>();if(current){if(categoryMode==="分析分类")for(const row of data.functionalRecords.filter(row=>row[1]===current))countyDetailMap.set(row[2],row[3]);else for(const row of data.records.filter(row=>row[1]===current&&matchesCategory(row))){const name=category.level===0?row[2]:category.level===1?row[3]:row[4];countyDetailMap.set(name,(countyDetailMap.get(name)||0)+row[5])}}const countyCategories=[...countyDetailMap].sort((a,b)=>b[1]-a[1]).slice(0,12),countyTotal=current?functionalTotalByCounty.get(current)||0:0;
  const currentContext=current?data.countyContext[current]:null,currentRaw=current?rawValues.get(current)||0:0,currentValue=current?normalizedValue(current):0,currentRank=current?ranked.findIndex(([county])=>county===current)+1:0,averageValue=values.size?[...values.values()].reduce((sum,value)=>sum+value,0)/values.size:0,difference=currentValue-averageValue;
  const currentLand=current?landDenominator(current):null;
  const denominator=measure==="count"?{label:"统计分母",value:"不适用（点位直接计数）"}:measure==="per10k"?{label:"2024年常住人口",value:`${fmt(currentContext?.residentPopulationWan||0,1)} 万人`}:measure==="perSqKm"?{label:"建设用地面积",value:`${fmt((currentContext?.constructionAreaHa||0)/100,1)} 平方公里`}:measure==="share"?{label:"区县全部有效功能型POI",value:`${fmt(current?functionalTotalByCounty.get(current)||0:0)} 个`}:measure==="lq"?{label:"都市圈当前功能占比",value:`${fmt(metroShare*100,1)}%`}:{label:currentLand?.label||"对应功能用地",value:`${fmt((currentLand?.ha||0)/100,2)} 平方公里`};
  const currentFunctions=new Map(data.functionalRecords.filter(row=>row[1]===current).map(row=>[row[2],row[3]])),functionValue=(name:string)=>currentFunctions.get(name)||0,functionLq=(name:string)=>{const total=functionalTotalByCounty.get(current||"")||1,metroFunction=data.functionalRecords.filter(row=>row[2]===name).reduce((s,r)=>s+r[3],0);return(functionValue(name)/total)/(metroFunction/data.meta.functionalPoiTotal)};
  const functionType=()=>{const service=["商业消费","餐饮休闲","公共管理","教育文化","医疗健康"].reduce((s,n)=>s+functionValue(n),0),industry=functionValue("产业就业")+functionValue("物流服务"),travel=functionValue("文旅生活"),traffic=functionValue("交通门户");return traffic&&functionLq("交通门户")>1.2?"港口交通门户型":industry>service*.55?"产业就业集聚型":travel>service*.55?"文旅生活服务型":service>industry*2?"综合服务中心型":"复合功能发展型"};
  const detailBase=categoryMode==="分析分类"?countyTotal:currentRaw;
  const serviceFunctions=["商业消费","教育文化","医疗健康","公共管理"],selectedFunction=functionalCategory==="ALL"?"商业消费":functionalCategory;
  return <section className="thematicModule"><nav className="landTopics poiTopics" aria-label="POI分析专题">{Object.entries(poiTopics).map(([key,item],index)=><button key={key} className={topic===key?"active":""} onClick={()=>setTopic(key as PoiTopic)}><b>0{index+1}</b><span>{item.name}<small>{item.question}</small></span></button>)}</nav><section className="thematicControls poiControls"><label>城市范围<select value={city} onChange={event=>setCity(event.target.value)}><option>全部</option><option>厦门市</option><option>漳州市</option><option>泉州市</option></select></label><label>分类口径<select value={categoryMode} onChange={event=>{const value=event.target.value as "分析分类"|"原始分类";setCategoryMode(value);if(value==="原始分类")setMeasure("count")}}><option>分析分类</option><option>原始分类</option></select></label>{categoryMode==="分析分类"?<label>POI功能<select value={functionalCategory} onChange={event=>setFunctionalCategory(event.target.value)}><option value="ALL">全部有效功能型POI</option>{data.meta.functionalCategories.map(name=><option key={name}>{name}</option>)}</select></label>:<details className="industryTree poiCategoryTree"><summary><span>POI原始类别（大类 → 中类 → 小类）</span><strong>{category.path}</strong></summary><div className="treePanel"><button className={category.level===0?"chosen":""} onClick={()=>setCategoryKey("0::")}>全部原始POI（{fmt(data.meta.poiTotal)}）</button>{data.categoryTree.map(major=><details key={major.name}><summary>{major.name}（{fmt(major.count)}）</summary><button className={category.level===1&&category.major===major.name?"chosen levelChoice":"levelChoice"} onClick={()=>setCategoryKey(`1::${major.name}`)}>选择“{major.name}”全部</button><div>{major.children?.map(middle=><details key={middle.name}><summary>{middle.name}（{fmt(middle.count)}）</summary><button className={category.level===2&&category.middle===middle.name?"chosen levelChoice":"levelChoice"} onClick={()=>setCategoryKey(`2::${major.name}::${middle.name}`)}>选择“{middle.name}”全部</button><div>{middle.children?.map(minor=><button key={minor.name} onClick={()=>setCategoryKey(`3::${major.name}::${middle.name}::${minor.name}`)}>{minor.name}（{fmt(minor.count)}）</button>)}</div></details>)}</div></details>)}</div></details>}<label>比较口径<select value={measure} onChange={event=>setMeasure(event.target.value as Measure)}>{(categoryMode==="原始分类"?["count","per10k","perSqKm"] as Measure[]:poiTopics[topic].measures).map(key=><option key={key} value={key}>{measures[key].name}</option>)}</select></label><label>定位区县<select value={selected||""} onChange={event=>setSelected(event.target.value||null)}><option value="">自动选择首位区县</option>{counties.map(county=><option key={county}>{county}</option>)}</select></label></section>
    <section className="mapFirstStage thematicMapFirstStage"><section className="populationStats"><article><span>当前POI总量</span><strong>{fmt(rawTotal)}</strong><small>{categoryName}</small></article><article><span>2024年常住人口</span><strong>{fmt(populationTotal,1)}</strong><small>万人 · 当前范围</small></article><article><span>建设用地</span><strong>{fmt(constructionTotal,1)}</strong><small>平方公里 · 当前范围</small></article><article><span>{definition.shortName}首位</span><strong className="populationTopName">{leader?.[0]||"暂无"}</strong><small>{leader?`${fmt(leader[1],definition.digits)} ${definition.unit}`:"无记录"}</small></article></section>
    {current&&categoryMode==="分析分类"&&<section className="landTopicInsight poiTopicInsight"><div className="topicIntro"><span>POI ANALYSIS</span><h2>{poiTopics[topic].name}</h2><p>{poiTopics[topic].question}。当前定位：{current}。</p></div>
      {topic==="overview"&&<div className="poiInsightGrid"><article><small>有效功能型POI</small><strong>{fmt(data.meta.functionalPoiTotal)}</strong><p>进入九类功能分析的去重点位</p></article><article><small>排除非功能记录</small><strong>{fmt(data.meta.excludedFunctionalRows)}</strong><p>地名、出入口、虚拟及道路附属记录</p></article><article><small>去除重复点位</small><strong>{fmt(data.meta.duplicateFunctionalRows)}</strong><p>同区县、同名称、同类型和同坐标重复</p></article></div>}
      {topic==="structure"&&<div className="topicBars poiTopicBars">{data.meta.functionalCategories.map(name=>{const value=functionValue(name);return <div key={name}><span>{name}</span><i><b style={{width:`${countyTotal?value/countyTotal*100:0}%`}}/></i><em>{fmt(countyTotal?value/countyTotal*100:0,1)}%</em><small>LQ {fmt(functionLq(name),2)}</small></div>})}</div>}
      {topic==="service"&&<div className="poiInsightGrid">{serviceFunctions.map(name=><article key={name}><small>每万人{name}节点</small><strong>{fmt((currentContext?.residentPopulationWan||0)?functionValue(name)/(currentContext?.residentPopulationWan||1):0,1)}</strong><p>{fmt(functionValue(name))} 个点位；仅反映节点数量</p></article>)}</div>}
      {topic==="center"&&<div className="poiTypeLayout"><article className="poiTypeCard"><small>初步功能类型</small><strong>{functionType()}</strong><p>依据九类POI规模、结构与区位熵识别，不作为行政等级或服务能力结论。</p></article><div className="topicBars poiTopicBars">{data.meta.functionalCategories.map(name=><div key={name}><span>{name}</span><i><b style={{width:`${Math.min(100,functionLq(name)/2*100)}%`}}/></i><em>LQ {fmt(functionLq(name),2)}</em></div>)}</div></div>}
      {topic==="match"&&<div className="poiInsightGrid"><article><small>当前功能节点</small><strong>{fmt(functionValue(selectedFunction))}</strong><p>{selectedFunction}</p></article><article><small>对应功能用地</small><strong>{fmt((currentLand?.ha||0)/100,2)}</strong><p>{currentLand?.label} · 平方公里</p></article><article><small>节点承载强度</small><strong>{fmt(currentValue,1)}</strong><p>个/平方公里；不等同土地利用效率</p></article></div>}
    </section>}
    <section className="thematicWorkspace"><ThematicMap features={data.countyBoundaries.features} values={values} activeCounties={active} selected={current||null} onSelect={setSelected} title={`厦漳泉${city==="全部"?"全域":city}${categoryName}${definition.shortName}分布`} subtitle={`${values.size}个区县 · 按${definition.name}动态分级`} legendTitle={`${categoryName}${definition.shortName}`} unit={definition.unit} digits={definition.digits}/><aside className="populationRanking"><div className="cardHead"><div><h2>区县POI排名</h2><p>{categoryName} · {definition.name}降序</p></div></div><div className="ranking">{ranked.map(([county,value],index)=><button key={county} className={current===county?"active":""} onClick={()=>setSelected(county)}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{county}</strong><small>{countyCity.get(county)}</small></span><em>{fmt(value,definition.digits)}</em></button>)}</div></aside></section></section>
    {current&&<section className="thematicDetailPanel poiDetailPanel"><div><span>{categoryMode==="分析分类"?"区县九类功能构成":`区县POI${category.level===0?"大类":category.level===1?"中类":"小类"}构成`}</span><h2>{current}</h2><p>{countyCity.get(current)} · 当前类别 {fmt(currentRaw)} 个</p><p>2024年常住人口 {fmt(currentContext?.residentPopulationWan||0,1)} 万人 · 建设用地 {fmt((currentContext?.constructionAreaHa||0)/100,1)} 平方公里</p><p>{definition.name} {fmt(currentValue,definition.digits)} {definition.unit}</p></div><div className="poiBars">{countyCategories.map(([name,value])=><div key={name}><span>{name}</span><i><b style={{width:`${countyCategories[0]?.[1]?value/countyCategories[0][1]*100:0}%`}}/></i><em>{fmt(value)}</em><small>{detailBase?fmt(value/detailBase*100,1):0}%</small></div>)}</div><div className="selectedMetricDetail"><div><span>当前POI指标</span><h3>{categoryName} · {definition.name}</h3><p>{definition.meaning}</p></div><article className="metricValue"><small>{current}指标值</small><strong>{fmt(currentValue,definition.digits)} {definition.unit}</strong><em>当前范围第 {currentRank} / {values.size} 位</em></article><article><small>当前类别POI数量</small><strong>{fmt(currentRaw)} 个</strong><em>实际分子</em></article><article><small>{denominator.label}</small><strong>{denominator.value}</strong><em>{measure==="count"?"数量口径":"实际分母"}</em></article><article><small>相对当前范围平均值</small><strong className={difference>=0?"positive":"negative"}>{difference>=0?"+":""}{fmt(difference,definition.digits)} {definition.unit}</strong><em>平均值 {fmt(averageValue,definition.digits)} {definition.unit}</em></article></div></section>}
    <section className="metricMethod poiMethod"><div><span>SUPPLY NORMALIZATION</span><h2>{definition.name}计算口径</h2><p>{definition.meaning}</p></div><article><small>计算公式</small><strong>{definition.formula}</strong></article><article><small>人口基准</small><strong>2024年区县常住人口</strong></article><article><small>空间基准</small><strong>区县建设用地面积（1 km² = 100 ha）</strong></article><aside><b>解读注意</b><p>POI是点位记录，未区分设施等级、规模、服务质量和服务半径；人均与密度指标用于横向比较，不能单独视为供需均衡结论。</p></aside></section>
    <div className="populationNote">POI数据：{data.meta.source}；常住人口：{data.meta.populationSource}；建设用地：{data.meta.landSource}。{data.meta.rule} {data.meta.normalizationRule}</div></section>;
}
