"use client";

import { useEffect, useMemo, useState } from "react";
import ThematicMap from "../mapkit/thematic-map";

type LandRecord={city:string;county:string;totalArea:number;agriculturalArea:number;constructionArea:number;unusedArea:number;developmentIntensity:number;agriculturalShare:number;unusedShare:number;urbanHousingShare:number;ruralHousingShare:number;urbanRuralHousingRatio:number;urbanHousingArea:number;ruralHousingArea:number;industrialArea:number;logisticsArea:number;industryWarehouseShare:number;industrialDevelopmentDensity:number;commercialShare:number;commercialArea:number;publicServiceShare:number;publicServiceArea:number;centralFunctionIndex:number;transportGatewayIndex:number;gatewayArea:number;roadShare:number;roadArea:number;portShare:number;portArea:number;miningArea:number;publicSpaceShare:number;publicSpaceArea:number;landUseMix:number;scope201Construction:number;scope202Construction:number;scope203Construction:number;scope201AIndustrial:number;scope202AIndustrial:number;scope203AIndustrial:number;lq:Record<string,number>};
type Payload={meta:{source:string;countyCount:number;year:string;areaUnit:string;note:string};countyBoundaries:{features:any[]};records:LandRecord[]};
type MetricKey=keyof Pick<LandRecord,"developmentIntensity"|"agriculturalShare"|"unusedShare"|"urbanHousingShare"|"ruralHousingShare"|"urbanRuralHousingRatio"|"industryWarehouseShare"|"industrialDevelopmentDensity"|"commercialShare"|"publicServiceShare"|"centralFunctionIndex"|"transportGatewayIndex"|"roadShare"|"portShare"|"publicSpaceShare"|"landUseMix">;
type Topic="development"|"urbanRural"|"industry"|"center"|"typology";
const topics:Record<Topic,{name:string;question:string;metrics:MetricKey[]}>= {
  development:{name:"国土开发强度",question:"哪里开发程度更高",metrics:["developmentIntensity","agriculturalShare","unusedShare"]},
  urbanRural:{name:"城乡建设形态",question:"建设空间偏城市集中还是乡村分散",metrics:["urbanHousingShare","ruralHousingShare","urbanRuralHousingRatio"]},
  industry:{name:"产业空间分工",question:"哪里偏制造、商业服务或港口物流",metrics:["industryWarehouseShare","industrialDevelopmentDensity","commercialShare","portShare"]},
  center:{name:"中心性与门户",question:"哪些区县承担服务中心和交通门户职能",metrics:["centralFunctionIndex","commercialShare","publicServiceShare","transportGatewayIndex","publicSpaceShare"]},
  typology:{name:"区县发展类型",question:"不只排名，而是识别功能类型",metrics:["developmentIntensity","industryWarehouseShare","centralFunctionIndex","transportGatewayIndex","ruralHousingShare"]},
};
type MetricDefinition={name:string;unit:string;digits:number;formula:string;numerator:string;denominator:string;interpretation:string;caution:string};
const metrics:Record<MetricKey,MetricDefinition>={
  developmentIntensity:{name:"建设用地开发强度",unit:"%",digits:1,formula:"建设用地面积 ÷ 行政区总面积 × 100%",numerator:"建设用地",denominator:"农用地＋建设用地＋未利用地",interpretation:"表示行政区国土空间中已转化为建设用地的比例。",caution:"值高表示建成化程度高，不直接等同于土地利用效率高。"},
  agriculturalShare:{name:"农用地占比",unit:"%",digits:1,formula:"农用地面积 ÷ 行政区总面积 × 100%",numerator:"农用地",denominator:"行政区总面积",interpretation:"表示农林牧渔等农用空间在区县国土中的份额。",caution:"占比受区县总面积和山地林地规模影响，不等同于耕地占比。"},
  unusedShare:{name:"未利用地占比",unit:"%",digits:1,formula:"未利用地面积 ÷ 行政区总面积 × 100%",numerator:"未利用地",denominator:"行政区总面积",interpretation:"表示源用地分类中未利用地的相对规模。",caution:"未利用地可包含难利用或生态敏感空间，不能直接解释为可开发后备土地。"},
  urbanHousingShare:{name:"城镇住宅占建设用地",unit:"%",digits:1,formula:"城镇住宅用地 ÷ 建设用地 × 100%",numerator:"城镇住宅用地",denominator:"建设用地",interpretation:"表示建设空间中城镇集中居住的用地份额。",caution:"不包含人口密度和建筑容积率，需与农村宅基地同时解读。"},
  ruralHousingShare:{name:"农村宅基地占建设用地",unit:"%",digits:1,formula:"农村宅基地 ÷ 建设用地 × 100%",numerator:"农村宅基地",denominator:"建设用地",interpretation:"表示村镇居住建设在区县建设空间中的份额。",caution:"值高表示乡村建设占重要地位，不直接等同于低效用地。"},
  urbanRuralHousingRatio:{name:"城乡居住结构比",unit:"",digits:2,formula:"城镇住宅用地 ÷ 农村宅基地",numerator:"城镇住宅用地",denominator:"农村宅基地",interpretation:"比较城镇集中居住与农村宅基地的相对规模。",caution:"农村宅基地很小时比值会异常偏高，需结合两类绝对面积。"},
  industryWarehouseShare:{name:"工业及仓储占建设用地",unit:"%",digits:1,formula:"（工业用地＋物流仓储用地）÷ 建设用地 × 100%",numerator:"工业＋物流仓储用地",denominator:"建设用地",interpretation:"表示建设空间中直接承载工业生产和物流仓储的比例。",caution:"反映用地结构，不直接代表产出、就业或产业质量。"},
  industrialDevelopmentDensity:{name:"产业开发密度",unit:"%",digits:1,formula:"（工业用地＋物流仓储用地）÷ 行政区总面积 × 100%",numerator:"工业＋物流仓储用地",denominator:"行政区总面积",interpretation:"表示产业用地在整个区县国土空间中的开发强度。",caution:"适合比较产业空间开发程度，但受区县面积大小影响。"},
  commercialShare:{name:"商业服务占建设用地",unit:"%",digits:1,formula:"商业服务业设施用地 ÷ 建设用地 × 100%",numerator:"商业服务业设施用地",denominator:"建设用地",interpretation:"表示建设空间中商业和服务业功能的用地份额。",caution:"仅衡量用地规模，不反映建筑容积率、营业额和服务半径。"},
  publicServiceShare:{name:"公共服务占建设用地",unit:"%",digits:1,formula:"（机关团体新闻出版＋科教文卫＋高教用地）÷ 建设用地 × 100%",numerator:"公共服务相关用地",denominator:"建设用地",interpretation:"表示建设空间中公共管理、教育、文化和卫生等用地的份额。",caution:"用地份额不等同于设施数量、床位学位或人均服务水平。"},
  centralFunctionIndex:{name:"中心功能指数",unit:"%",digits:1,formula:"（商业服务＋公共服务＋公园绿地＋广场）÷ 建设用地 × 100%",numerator:"商业＋公服＋公共空间用地",denominator:"建设用地",interpretation:"用服务、公服和公共空间的组合份额表征城市中心功能。",caution:"为用地结构代理指标，并非城市中心性的综合评价。"},
  transportGatewayIndex:{name:"交通门户指数",unit:"%",digits:1,formula:"（铁路＋轨道＋机场＋港口＋场站＋物流仓储用地）÷ 建设用地 × 100%",numerator:"门户交通与物流用地",denominator:"建设用地",interpretation:"表示区县建设空间中承载对外交通和物流门户功能的份额。",caution:"不包含实际客货流量、时间可达性和网络中心性。"},
  roadShare:{name:"公路用地占建设用地",unit:"%",digits:1,formula:"公路用地 ÷ 建设用地 × 100%",numerator:"公路用地",denominator:"建设用地",interpretation:"表示公路用地在建设空间中的份额。",caution:"占比高不等于交通条件更好，可能受过境公路或建设用地分母较小影响。"},
  portShare:{name:"港口码头占建设用地",unit:"%",digits:1,formula:"港口码头用地 ÷ 建设用地 × 100%",numerator:"港口码头用地",denominator:"建设用地",interpretation:"表示港口码头用地在建设空间中的份额。",caution:"仅反映用地结构，需结合港口吞吐量判断实际门户能级。"},
  publicSpaceShare:{name:"公共空间占建设用地",unit:"%",digits:1,formula:"（公园与绿地＋广场用地）÷ 建设用地 × 100%",numerator:"公园绿地＋广场用地",denominator:"建设用地",interpretation:"表示建设空间中公园、绿地和广场等公共开放空间的份额。",caution:"不反映公众实际可达性、绿地品质和服务覆盖率。"},
  landUseMix:{name:"建设用地混合度",unit:"",digits:3,formula:"-Σ(pᵢ × ln pᵢ) ÷ ln(7)",numerator:"居住、产业、商业服务、公共服务、交通门户、公共空间、其他建设七类的信息熵",denominator:"七类功能完全均衡时的最大熵 ln(7)",interpretation:"将七类建设用地功能的香农熵归一化到0—1；越接近1表示结构越均衡多样。",caution:"高混合度只表示面积分布均衡，不代表功能之间的空间邻近或实际互动。"},
};
const fmt=(value:number,digits=0)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:digits}).format(value);
const metricParts=(row:LandRecord,metric:MetricKey)=>{
  const area=(label:string,value:number)=>({label,value:`${fmt(value,1)} 公顷`});
  if(metric==="developmentIntensity")return{numerator:area("建设用地",row.constructionArea),denominator:area("行政区总面积",row.totalArea)};
  if(metric==="agriculturalShare")return{numerator:area("农用地",row.agriculturalArea),denominator:area("行政区总面积",row.totalArea)};
  if(metric==="unusedShare")return{numerator:area("未利用地",row.unusedArea),denominator:area("行政区总面积",row.totalArea)};
  if(metric==="urbanHousingShare")return{numerator:area("城镇住宅用地",row.urbanHousingArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="ruralHousingShare")return{numerator:area("农村宅基地",row.ruralHousingArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="urbanRuralHousingRatio")return{numerator:area("城镇住宅用地",row.urbanHousingArea),denominator:area("农村宅基地",row.ruralHousingArea)};
  if(metric==="industryWarehouseShare")return{numerator:area("工业＋物流仓储用地",row.industryWarehouseShare*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="industrialDevelopmentDensity")return{numerator:area("工业＋物流仓储用地",row.industrialDevelopmentDensity*row.totalArea),denominator:area("行政区总面积",row.totalArea)};
  if(metric==="commercialShare")return{numerator:area("商业服务业设施用地",row.commercialShare*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="publicServiceShare")return{numerator:area("公共服务相关用地",row.publicServiceShare*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="centralFunctionIndex")return{numerator:area("商业＋公服＋公共空间用地",row.centralFunctionIndex*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="transportGatewayIndex")return{numerator:area("门户交通与物流用地",row.transportGatewayIndex*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="roadShare")return{numerator:area("公路用地",row.roadArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="portShare")return{numerator:area("港口码头用地",row.portArea),denominator:area("建设用地",row.constructionArea)};
  if(metric==="publicSpaceShare")return{numerator:area("公园绿地＋广场用地",row.publicSpaceShare*row.constructionArea),denominator:area("建设用地",row.constructionArea)};
  return{numerator:{label:"标准化香农熵",value:fmt(row.landUseMix,3)},denominator:{label:"理论取值范围",value:"0—1"}};
};

export default function LandUseModule(){
  const [data,setData]=useState<Payload|null>(null),[topic,setTopic]=useState<Topic>("development"),[city,setCity]=useState("全部"),[metric,setMetric]=useState<MetricKey>("developmentIntensity"),[selected,setSelected]=useState<string|null>(null);
  useEffect(()=>{fetch("/data/land-use.json").then(response=>response.json()).then(setData)},[]);
  useEffect(()=>setSelected(null),[city,metric]);
  useEffect(()=>{setMetric(topics[topic].metrics[0]);setSelected(null)},[topic]);
  const records=useMemo(()=>data?.records.filter(row=>city==="全部"||row.city===city)||[],[data,city]);
  if(!data)return <section className="thematicLoading">正在载入用地数据…</section>;
  const definition=metrics[metric],valueFor=(row:LandRecord)=>metric==="landUseMix"||metric==="urbanRuralHousingRatio"?row[metric]:row[metric]*100,values=new Map(records.map(row=>[row.county,valueFor(row)])),active=new Set(records.map(row=>row.county)),ranked=[...records].sort((a,b)=>valueFor(b)-valueFor(a)),current=records.find(row=>row.county===selected)||ranked[0];
  const average=records.length?records.reduce((sum,row)=>sum+valueFor(row),0)/records.length:0,totalConstruction=records.reduce((sum,row)=>sum+row.constructionArea,0),top=ranked[0];
  const composition=current?[{name:"农用地",value:current.agriculturalArea,color:"#79aa86"},{name:"建设用地",value:current.constructionArea,color:"#d89b58"},{name:"未利用地",value:current.unusedArea,color:"#aab7b0"}]:[];
  const currentValue=current?valueFor(current):0,currentRank=current?ranked.findIndex(row=>row.county===current.county)+1:0,currentParts=current?metricParts(current,metric):null,difference=currentValue-average;
  const med=(key:keyof LandRecord)=>{const sorted=[...data.records].map(row=>Number(row[key])).sort((a,b)=>a-b);return sorted[Math.floor(sorted.length/2)]},thresholds={development:med("developmentIntensity"),industry:med("industryWarehouseShare"),center:med("centralFunctionIndex"),gateway:med("transportGatewayIndex"),rural:med("ruralHousingShare")};
  const landType=(row:LandRecord)=>row.transportGatewayIndex>=thresholds.gateway*1.5?"港口物流门户型":row.centralFunctionIndex>=thresholds.center*1.5&&row.developmentIntensity>=thresholds.development?"综合服务核心型":row.industryWarehouseShare>=thresholds.industry*1.25&&row.developmentIntensity>=thresholds.development?"制造业集聚型":row.developmentIntensity>=thresholds.development&&row.ruralHousingShare>=thresholds.rural?"城市拓展承接型":row.centralFunctionIndex>=thresholds.center?"县域综合中心型":"农业生态腹地型";
  const cityOverview=["厦门市","漳州市","泉州市"].map(name=>{const rows=data.records.filter(row=>row.city===name),total=rows.reduce((s,r)=>s+r.totalArea,0),agri=rows.reduce((s,r)=>s+r.agriculturalArea,0),construction=rows.reduce((s,r)=>s+r.constructionArea,0),unused=rows.reduce((s,r)=>s+r.unusedArea,0);return{name,total,agri,construction,unused}});
  const typeCounts=new Map<string,number>();for(const row of records){const type=landType(row);typeCounts.set(type,(typeCounts.get(type)||0)+1)}
  return <section className="thematicModule"><nav className="landTopics" aria-label="用地分析专题">{Object.entries(topics).map(([key,item],index)=><button key={key} className={topic===key?"active":""} onClick={()=>setTopic(key as Topic)}><b>0{index+1}</b><span>{item.name}<small>{item.question}</small></span></button>)}</nav><section className="thematicControls"><label>城市范围<select value={city} onChange={event=>setCity(event.target.value)}><option>全部</option><option>厦门市</option><option>漳州市</option><option>泉州市</option></select></label><label>地图指标<select value={metric} onChange={event=>setMetric(event.target.value as MetricKey)}>{topics[topic].metrics.map(key=><option key={key} value={key}>{metrics[key].name}</option>)}</select></label><label>定位区县<select value={selected||""} onChange={event=>setSelected(event.target.value||null)}><option value="">自动选择首位区县</option>{records.map(row=><option key={row.county}>{row.county}</option>)}</select></label></section>
    <section className="mapFirstStage thematicMapFirstStage"><section className="populationStats"><article><span>当前区县</span><strong>{records.length}</strong><small>统一口径横向比较</small></article><article><span>平均{definition.name}</span><strong>{fmt(average,definition.digits)}{definition.unit}</strong><small>当前城市范围</small></article><article><span>建设用地合计</span><strong>{fmt(totalConstruction,0)}</strong><small>公顷</small></article><article><span>指标首位</span><strong className="populationTopName">{top?.county||"暂无"}</strong><small>{top?`${fmt(valueFor(top),definition.digits)}${definition.unit}`:"无记录"}</small></article></section>
    <section className="landTopicInsight"><header><span>LAND TOPIC</span><h2>{topics[topic].name}</h2><p>{topics[topic].question}</p>{topic==="typology"&&<small>类型识别以都市圈28区县中位数为基准，门户、中心和产业特征达到基准的1.25—1.5倍时优先识别专业化类型。</small>}</header>{topic==="development"&&<div className="cityLandStack">{cityOverview.map(row=><article key={row.name}><strong>{row.name}</strong><div><i style={{width:`${row.agri/row.total*100}%`}}/><i style={{width:`${row.construction/row.total*100}%`}}/><i style={{width:`${row.unused/row.total*100}%`}}/></div><p><span>农用 {fmt(row.agri/row.total*100,1)}%</span><span>建设 {fmt(row.construction/row.total*100,1)}%</span><span>未利用 {fmt(row.unused/row.total*100,1)}%</span></p></article>)}</div>}{topic==="urbanRural"&&current&&<div className="topicBars">{[["城镇住宅",current.urbanHousingShare*100],["农村宅基地",current.ruralHousingShare*100]].map(([name,value])=><article key={String(name)}><span>{name}</span><i><b style={{width:`${Math.min(100,Number(value))}%`}}/></i><strong>{fmt(Number(value),1)}%</strong></article>)}<h3>{current.county}权属范围内建设用地</h3>{[["201 城市范围",current.scope201Construction],["202 建制镇范围",current.scope202Construction],["203 村庄范围",current.scope203Construction]].map(([name,value])=><article key={String(name)}><span>{name}</span><i><b style={{width:`${Math.min(100,Number(value)/Math.max(current.scope201Construction,current.scope202Construction,current.scope203Construction,1)*100)}%`}}/></i><strong>{fmt(Number(value),0)} ha</strong></article>)}</div>}{topic==="industry"&&current&&<div className="topicBars">{[["工业用地",current.industrialArea],["物流仓储",current.logisticsArea],["商业服务",current.commercialArea],["港口码头",current.portArea]].map(([name,value])=><article key={String(name)}><span>{name}</span><i><b style={{width:`${Math.min(100,Number(value)/Math.max(current.industrialArea,current.logisticsArea,current.commercialArea,current.portArea,1)*100)}%`}}/></i><strong>{fmt(Number(value),0)} ha</strong></article>)}</div>}{topic==="center"&&current&&<div className="topicBars">{[["商业服务",current.commercialShare],["公共服务",current.publicServiceShare],["公共空间",current.publicSpaceShare],["交通门户",current.transportGatewayIndex]].map(([name,value])=><article key={String(name)}><span>{name}</span><i><b style={{width:`${Math.min(100,Number(value)*300)}%`}}/></i><strong>{fmt(Number(value)*100,1)}%</strong></article>)}</div>}{topic==="typology"&&current&&<div className="landTypePanel"><article><span>{current.county}</span><strong>{landType(current)}</strong><p>开发强度 {fmt(current.developmentIntensity*100,1)}% · 工业仓储 {fmt(current.industryWarehouseShare*100,1)}% · 中心功能 {fmt(current.centralFunctionIndex*100,1)}% · 门户功能 {fmt(current.transportGatewayIndex*100,1)}%</p></article><div>{[...typeCounts].sort((a,b)=>b[1]-a[1]).map(([name,count])=><span key={name}><b>{count}</b>{name}</span>)}</div></div>}</section>
    <section className="thematicWorkspace"><ThematicMap features={data.countyBoundaries.features} values={values} activeCounties={active} selected={current?.county||null} onSelect={setSelected} title={`厦漳泉${city==="全部"?"全域":city}${definition.name}分布`} subtitle={`${records.length}个区县 · ${data.meta.year}`} legendTitle={definition.name} unit={definition.unit} digits={definition.digits}/><aside className="populationRanking"><div className="cardHead"><div><h2>{definition.name}排名</h2><p>按当前指标降序</p></div></div><div className="ranking">{ranked.map((row,index)=><button key={row.county} className={current?.county===row.county?"active":""} onClick={()=>setSelected(row.county)}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{row.county}</strong><small>{row.city}</small></span><em>{fmt(valueFor(row),definition.digits)}{definition.unit}</em></button>)}</div></aside></section></section>
    {current&&currentParts&&<section className="thematicDetailPanel"><div><span>区县用地结构</span><h2>{current.county}</h2><p>{current.city} · 行政区总面积 {fmt(current.totalArea)} 公顷</p></div><div className="landComposition">{composition.map(item=><div key={item.name}><span><i style={{background:item.color}}/>{item.name}</span><strong>{fmt(item.value)} 公顷</strong><small>{fmt(item.value/current.totalArea*100,1)}%</small></div>)}</div><div className="lqPanel"><strong>建设功能区位熵 LQ</strong>{Object.entries(current.lq).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><span>{name}</span><i><b style={{width:`${Math.min(100,value/5*100)}%`}}/></i><em className={value>1?"high":""}>{fmt(value,2)}</em></div>)}</div><div className="selectedMetricDetail"><div><span>当前指标</span><h3>{definition.name}</h3><p>{definition.interpretation}</p></div><article className="metricValue"><small>{current.county}指标值</small><strong>{fmt(currentValue,definition.digits)}{definition.unit}</strong><em>当前范围第 {currentRank} / {records.length} 位</em></article><article><small>{currentParts.numerator.label}</small><strong>{currentParts.numerator.value}</strong><em>实际分子</em></article><article><small>{currentParts.denominator.label}</small><strong>{currentParts.denominator.value}</strong><em>实际分母</em></article><article><small>相对当前范围平均值</small><strong className={difference>=0?"positive":"negative"}>{difference>=0?"+":""}{fmt(difference,definition.digits)}{definition.unit}</strong><em>平均值 {fmt(average,definition.digits)}{definition.unit}</em></article></div></section>}
    <section className="metricMethod"><div><span>INDICATOR METHOD</span><h2>{definition.name}计算逻辑</h2><p>{definition.interpretation}</p></div><article><small>计算公式</small><strong>{definition.formula}</strong></article><article><small>分子口径</small><strong>{definition.numerator}</strong></article><article><small>分母口径</small><strong>{definition.denominator}</strong></article><aside><b>解读注意</b><p>{definition.caution}</p></aside></section>
    <div className="populationNote">数据源：{data.meta.source}。面积统一采用公顷；{data.meta.note}</div></section>;
}
